"""DRAFT watermark utility for all generated legal documents.

Every document produced by the legal module MUST pass through
:func:`add_draft_watermark` before being stored or returned to the caller.
"""

from __future__ import annotations

WATERMARK_LINE = (
    "\u2550\u2550\u2550 DRAFT \u2014 FOR REVIEW ONLY \u2014 NOT A COURT FILING \u2550\u2550\u2550"
)

DISCLAIMER = (
    "This document was generated by an automated system. It requires review "
    "by a qualified attorney or the pro se petitioner before any court "
    "submission. All legal conclusions, statutory citations, and factual "
    "assertions must be independently verified."
)


def add_draft_watermark(content: str) -> str:
    """Prepend and append DRAFT notices and disclaimer to *content*.

    Parameters
    ----------
    content:
        The raw rendered document body (HTML, Markdown, or plain text).

    Returns
    -------
    str
        The document wrapped with watermark header, disclaimer, and
        watermark footer.
    """
    header = f"{WATERMARK_LINE}\n\n{DISCLAIMER}\n\n{WATERMARK_LINE}\n\n"
    footer = f"\n\n{WATERMARK_LINE}\n\n{DISCLAIMER}\n\n{WATERMARK_LINE}"
    return f"{header}{content}{footer}"
